ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.example.DatabaseFactoryKt.configureDatabase
      - com.example.SerializationKt.configureSerialization
      - com.example.HTTPKt.configureHTTP
      - com.example.SecurityKt.configureSecurity
      - com.example.RoutingKt.configureRouting

db:
  jdbcUrl: "jdbc:postgresql://localhost:5432/shoproz"
  user: "postgres"
  password: "postgres"
  driver: "org.postgresql.Driver"
  maxPoolSize: 10

jwt:
  secret: "change-me-please-very-secret"
  issuer: "shoproz"
  audience: "shoproz-users"
  realm: "shoproz access"
  accessTtlMinutes: 30
  refreshTtlDays: 30

